-- clock_cal_combi — compact clock + calendar side by side

conky.config = {
    background = true,
    double_buffer = true,
    use_xft = true,
    font = 'Sans:size=10',
    own_window_class = 'Conky',
    own_window_title = 'Conky Clock Calendar Combi',
    own_window = true,
    own_window_type = 'normal',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    alignment = 'top_left',
    gap_x = 356,
    gap_y = 60,
    update_interval = 1,
    total_run_times = 0,
    minimum_width = 340,
    minimum_height = 180,
    border_inner_margin = 0,
    border_outer_margin = 0,
    border_width = 0,
    lua_load = 'clock_cal_combi.lua',
    lua_draw_hook_pre = 'conky_core_main',
    lua_mouse_hook = 'conky_on_mouse',
    lua_shutdown_hook = 'conky_cleanup',
}

conky.text = [[

]]
