-- google — compact Google modules dashboard

conky.config = {
    background = true,
    double_buffer = true,
    use_xft = true,
    font = 'Sans:size=10',
    own_window_class = 'Conky',
    own_window_title = 'Conky Google',
    own_window = true,
    own_window_type = 'normal',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    alignment = 'top_right',
    gap_x = 71,
    gap_y = 360,
    update_interval = 1,
    total_run_times = 0,
    minimum_width = 430,
    minimum_height = 340,
    border_inner_margin = 0,
    border_outer_margin = 0,
    border_width = 0,
    lua_load = 'google.lua',
    lua_draw_hook_pre = 'conky_core_main',
    lua_mouse_hook = 'conky_on_mouse',
    lua_shutdown_hook = 'conky_cleanup',
}

conky.text = [[
${lua conky_google_update}
]]
